// <auto-generated />
using System;
using MercurySurvey.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercurySurvey.Migrations
{
    [DbContext(typeof(NoteContext))]
    [Migration("20190924161422_FixedUserHeightDataTypeError")]
    partial class FixedUserHeightDataTypeError
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MercurySurvey.Models.Answer", b =>
                {
                    b.Property<Guid>("AnswerGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Ctime");

                    b.Property<DateTime>("Mtime");

                    b.Property<Guid>("Question");

                    b.Property<Guid>("QuestionnaireGuid");

                    b.Property<int>("RecordId");

                    b.Property<Guid>("Userid");

                    b.HasKey("AnswerGuid");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("MercurySurvey.Models.Question", b =>
                {
                    b.Property<Guid>("QuestionGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Calculator");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Ctime");

                    b.Property<bool>("IsEnable");

                    b.Property<int>("QuestionPK");

                    b.Property<string>("Type");

                    b.Property<Guid>("Version");

                    b.HasKey("QuestionGuid");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("MercurySurvey.Models.QuestionQueue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Ctime");

                    b.Property<Guid>("QuestionVersion");

                    b.Property<Guid>("QuestionnaireGuid");

                    b.Property<Guid>("QueueGuid");

                    b.Property<Guid>("QueueUser");

                    b.HasKey("ID");

                    b.ToTable("QuestionQueue");
                });

            modelBuilder.Entity("MercurySurvey.Models.Questionnaire", b =>
                {
                    b.Property<Guid>("QuestionnaireGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Calculator");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Ctime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Question");

                    b.Property<int>("QuestionnairePK");

                    b.Property<Guid>("Version");

                    b.HasKey("QuestionnaireGuid");

                    b.ToTable("Questionnaire");
                });

            modelBuilder.Entity("MercurySurvey.Models.Result", b =>
                {
                    b.Property<Guid>("AnswerGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("Ctime");

                    b.Property<Guid>("Question");

                    b.Property<Guid>("QuestionnaireGuid");

                    b.Property<int>("RecordId");

                    b.Property<Guid>("Userid");

                    b.HasKey("AnswerGuid");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("MercurySurvey.Models.TraditionalMedicalConstitution.UserInformationRecord", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<double>("Height");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("UserGender");

                    b.Property<Guid>("UserGuid");

                    b.Property<string>("UserName");

                    b.Property<double>("Weight");

                    b.HasKey("RecordID");

                    b.ToTable("UserInformation");
                });

            modelBuilder.Entity("MercurySurvey.Models.UploadFile", b =>
                {
                    b.Property<Guid>("FileGuid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Ctime");

                    b.Property<byte[]>("Files");

                    b.Property<Guid>("UserGuid");

                    b.HasKey("FileGuid");

                    b.ToTable("UploadFile");
                });
#pragma warning restore 612, 618
        }
    }
}
